/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package defencesystem;

import java.awt.Dimension;

/**
 *
 * @author Administrator
 */
public class MainControllerWindow extends javax.swing.JFrame {
    private ControlRoom DefenceObjRef;

    /**
     * Creates new form MainControllerWindow
     */
    public MainControllerWindow(ControlRoom DefenceObjRef) {
        this.DefenceObjRef=DefenceObjRef;
        initComponents();
        setPreferredSize(new Dimension(415, 340));
        pack(); 
        setVisible(true);
        jTextAreaShowMsg.setEditable(false);
        jTextFieldTypeMsg.setEditable(false);
        sendRefToControlRoom();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSlider = new javax.swing.JSlider();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaShowMsg = new javax.swing.JTextArea();
        jTextFieldTypeMsg = new javax.swing.JTextField();
        jButtonSend = new javax.swing.JButton();
        jCheckBoxAll = new javax.swing.JCheckBox();
        jCheckBoxHelicopter = new javax.swing.JCheckBox();
        jCheckBoxSubmarine = new javax.swing.JCheckBox();
        jCheckBoxTank = new javax.swing.JCheckBox();
        jrbtnAreaClear = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Controller");
        setLocation(new java.awt.Point(430, 0));
        setSize(new java.awt.Dimension(300, 400));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Helicopter", "Submarine", "Tank" }));
        jComboBox1.setToolTipText("");
        jComboBox1.setName(""); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jLabel1.setText("Fuel Amount  ");

        jLabel2.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jLabel2.setText("Position   ");

        jLabel3.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jLabel3.setText("Ammo Amount ");

        jLabel4.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jLabel4.setText("Soldier Count");

        jSlider.setMajorTickSpacing(20);
        jSlider.setPaintLabels(true);
        jSlider.setPaintTicks(true);
        jSlider.setSnapToTicks(true);
        jSlider.setValue(0);
        jSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderStateChanged(evt);
            }
        });

        jTextAreaShowMsg.setColumns(20);
        jTextAreaShowMsg.setRows(5);
        jScrollPane1.setViewportView(jTextAreaShowMsg);

        jTextFieldTypeMsg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jButtonSend.setText("Send");
        jButtonSend.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jButtonSendStateChanged(evt);
            }
        });
        jButtonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendActionPerformed(evt);
            }
        });

        jCheckBoxAll.setFont(new java.awt.Font("SimSun-ExtB", 1, 12)); // NOI18N
        jCheckBoxAll.setText("All");
        jCheckBoxAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAllActionPerformed(evt);
            }
        });

        jCheckBoxHelicopter.setFont(new java.awt.Font("SimSun-ExtB", 1, 12)); // NOI18N
        jCheckBoxHelicopter.setText("Helicopter");
        jCheckBoxHelicopter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxHelicopterActionPerformed(evt);
            }
        });

        jCheckBoxSubmarine.setFont(new java.awt.Font("SimSun-ExtB", 1, 12)); // NOI18N
        jCheckBoxSubmarine.setText("Submarine");
        jCheckBoxSubmarine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSubmarineActionPerformed(evt);
            }
        });

        jCheckBoxTank.setFont(new java.awt.Font("SimSun-ExtB", 1, 12)); // NOI18N
        jCheckBoxTank.setText("Tank");
        jCheckBoxTank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTankActionPerformed(evt);
            }
        });

        jrbtnAreaClear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jrbtnAreaClear.setText("Area Clear");
        jrbtnAreaClear.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jrbtnAreaClearItemStateChanged(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Collect Informations");

        jLabel5.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        jLabel5.setText("Send Message");

        jLabel6.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jLabel6.setText("0");

        jLabel7.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jLabel7.setText("0");

        jLabel9.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jLabel9.setText("0");

        jLabel10.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jLabel10.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10)))
                                    .addComponent(jLabel8)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jrbtnAreaClear, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBoxAll, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBoxHelicopter, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBoxSubmarine)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBoxTank, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldTypeMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel10)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jrbtnAreaClear, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxAll)
                    .addComponent(jCheckBoxHelicopter)
                    .addComponent(jCheckBoxSubmarine)
                    .addComponent(jCheckBoxTank))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldTypeMsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jButtonSend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jComboBox1.getAccessibleContext().setAccessibleName("");
        jComboBox1.getAccessibleContext().setAccessibleDescription("Select Defence");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed
    
//-----------After Pressed AreaClear Button call Control Room--------------------- 
    private void jrbtnAreaClearItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jrbtnAreaClearItemStateChanged
        if(jrbtnAreaClear.isSelected()){
            DefenceObjRef.callAreaClear("Area Clear");
        }else {
            DefenceObjRef.callAreaClear("Area Not Clear");
        }
    }//GEN-LAST:event_jrbtnAreaClearItemStateChanged
//--------------------After Drag Jslider call Control Room--------------------- 
    private void jSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderStateChanged
         DefenceObjRef.callsliderChangers(jSlider.getValue());
    }//GEN-LAST:event_jSliderStateChanged
//--------------------Press Send and Go msg to ArrayList--------------------- 
    private void jButtonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendActionPerformed
        DefenceObjRef.setMsgToArrayList("Main:"+jTextFieldTypeMsg.getText());
        jTextFieldTypeMsg.setText("");
    }//GEN-LAST:event_jButtonSendActionPerformed

    private void jButtonSendStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jButtonSendStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSendStateChanged

//-----------------------After tik "ALL" enable All Msg Send Area---------------------
    private void jCheckBoxAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAllActionPerformed
        if(jCheckBoxAll.isSelected()){
            jTextFieldTypeMsg.setEditable(true);
            DefenceObjRef.enableAllMsgSendTextArea(true);
        }else{
            jTextFieldTypeMsg.setEditable(false);
            DefenceObjRef.enableAllMsgSendTextArea(false);
        }
    }//GEN-LAST:event_jCheckBoxAllActionPerformed

//-----------------------After tik "Helicopter" enable All Msg Send Area---------------------
    private void jCheckBoxHelicopterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxHelicopterActionPerformed
       if(jCheckBoxHelicopter.isSelected()){
            jTextFieldTypeMsg.setEditable(true);
            DefenceObjRef.enableCustomMsgSendTextArea(true,0);
            
        }else{
            jTextFieldTypeMsg.setEditable(false);
            DefenceObjRef.enableCustomMsgSendTextArea(false,0);
        }
    }//GEN-LAST:event_jCheckBoxHelicopterActionPerformed
//-----------------------After tik "Tank" enable All Msg Send Area---------------------
    private void jCheckBoxTankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTankActionPerformed
        if(jCheckBoxTank.isSelected()){
            jTextFieldTypeMsg.setEditable(true);
            DefenceObjRef.enableCustomMsgSendTextArea(true,2);
            
        }else{
            jTextFieldTypeMsg.setEditable(false);
            DefenceObjRef.enableCustomMsgSendTextArea(false,2);
        }
    }//GEN-LAST:event_jCheckBoxTankActionPerformed
//-----------------------After tik "Submarine" enable All Msg Send Area---------------------
    private void jCheckBoxSubmarineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSubmarineActionPerformed
        if(jCheckBoxSubmarine.isSelected()){
            jTextFieldTypeMsg.setEditable(true);
            DefenceObjRef.enableCustomMsgSendTextArea(true,1);
            
        }else{
            jTextFieldTypeMsg.setEditable(false);
            DefenceObjRef.enableCustomMsgSendTextArea(false,1);
        }
    }//GEN-LAST:event_jCheckBoxSubmarineActionPerformed

//-------------------------Send Reffence To controller--------------------------
    private void  sendRefToControlRoom(){
        DefenceObjRef.mainControllerRefSet(this);
    }
 //-------------------------Get Text and Show it--------------------------------
    public void setMsgtojTextAreaShowMsg(String text){
            jTextAreaShowMsg.append(text+"\n");
    }
//-------------------------Get Text and Show it--------------------------------
    public void clearTextArea(){
        jTextAreaShowMsg.setText("");
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSend;
    private javax.swing.JCheckBox jCheckBoxAll;
    private javax.swing.JCheckBox jCheckBoxHelicopter;
    private javax.swing.JCheckBox jCheckBoxSubmarine;
    private javax.swing.JCheckBox jCheckBoxTank;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider;
    private javax.swing.JTextArea jTextAreaShowMsg;
    private javax.swing.JTextField jTextFieldTypeMsg;
    private javax.swing.JRadioButton jrbtnAreaClear;
    // End of variables declaration//GEN-END:variables

}

